school_app/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.urls import include, path

# urlpatterns = [
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("", include("apps.corecode.urls")),
#     path("student/", include("apps.students.urls")),
#     path("staff/", include("apps.staffs.urls")),
#     path("finance/", include("apps.finance.urls")),
#     path("result/", include("apps.result.urls")),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# from django.conf import settings
# from django.conf.urls.static import static
# from django.urls import include, path
# from django.contrib.auth import views as auth_views
# from . import views

# urlpatterns = [
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("", include("apps.corecode.urls")),
#     path("student/", include("apps.students.urls")),
#     path("staff/", include("apps.staffs.urls")),
#     path("finance/", include("apps.finance.urls")),
#     path("result/", include("apps.result.urls")),


#     # path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
#     # path('signup/', views.signup, name='signup'),
#     # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
# ]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin  # Import the admin module
from django.contrib.auth import views as auth_views
from . import views  
from django.contrib import admin
from django.urls import path, include
# from .views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),  # Add this line for the admin panel
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path('index/', views.index, name='index'),  # This points to the index view
    path('password_change/', views.change_password, name='password_change'),
    path('password_change/done/', views.index, name='password_change_done'),

    #  path('profile/', profile_view, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/corecode/models.py
from django.db import models

# Create your models here.


class SiteConfig(models.Model):
    """Site Configurations"""

    key = models.SlugField()
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.key


class AcademicSession(models.Model):
    """Academic Session"""

    name = models.CharField(max_length=200, unique=True)
    current = models.BooleanField(default=True)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name


class AcademicTerm(models.Model):
    """Academic Term"""

    name = models.CharField(max_length=20, unique=True)
    current = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Subject(models.Model):
    """Subject"""

    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class StudentClass(models.Model):
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        verbose_name = "Class"
        verbose_name_plural = "Classes"
        ordering = ["name"]

    def __str__(self):
        return self.name
    
import uuid

def get_image_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return filename

# models.py 

from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to=get_image_filename, blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=254, blank=True)


    def __str__(self):
        return self.user.username

##### for sign-up:
  
# models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    

    def __str__(self):
        return self.user.username

apps/corecode/forms.py
from django import forms
from django.forms import ModelForm, modelformset_factory

from .models import (
    AcademicSession,
    AcademicTerm,
    SiteConfig,
    StudentClass,
    Subject,
)

SiteConfigForm = modelformset_factory(
    SiteConfig,
    fields=(
        "key",
        "value",
    ),
    extra=0,
)


class AcademicSessionForm(ModelForm):
    prefix = "Academic Session"

    class Meta:
        model = AcademicSession
        fields = ["name", "current"]


class AcademicTermForm(ModelForm):
    prefix = "Academic Term"

    class Meta:
        model = AcademicTerm
        fields = ["name", "current"]


class SubjectForm(ModelForm):
    prefix = "Subject"

    class Meta:
        model = Subject
        fields = ["name"]


class StudentClassForm(ModelForm):
    prefix = "Class"

    class Meta:
        model = StudentClass
        fields = ["name"]


class CurrentSessionForm(forms.Form):
    current_session = forms.ModelChoiceField(
        queryset=AcademicSession.objects.all(),
        help_text='Click <a href="/session/create/?next=current-session/">here</a> to add new session',
    )
    current_term = forms.ModelChoiceField(
        queryset=AcademicTerm.objects.all(),
        help_text='Click <a href="/term/create/?next=current-session/">here</a> to add new term',
    )



# # forms.py

# from django import forms
# from django.contrib.auth.models import User
# from .models import Profile

# class UserUpdateForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['username']

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['first_name', 'last_name', 'profile_picture']


# forms.py

# from django import forms
# from django.contrib.auth.models import User
# from .models import Profile
# from django.contrib.auth.forms import PasswordChangeForm

# class UserUpdateForm(forms.ModelForm):
#     # email = forms.EmailField()
#     email = forms.EmailField(required=False)

#     class Meta:
#         model = User
#         fields = ['username', 'email', 'first_name', 'last_name']

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['profile_picture','email']



## sub admin

# # forms.py

# from django import forms
# from django.contrib.auth.models import User
# from .models import Profile
# from django.contrib.auth.forms import PasswordChangeForm

# class UserUpdateForm(forms.ModelForm):
#     email = forms.EmailField()

#     class Meta:
#         model = User
#         fields = ['username', 'email', 'first_name', 'last_name']

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['profile_picture', 'first_name', 'last_name', 'email']

# class PasswordChangeForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['password']






#####profile and edit profile

# forms.py

from django import forms
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_picture', 'email')

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

templates/change_password.html
<!-- {% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.old_password.label_tag }}<br>
      {{ form.old_password }}
    </div>
    <div class="form-group">
      {{ form.new_password1.label_tag }}<br>
      <div class="input-group">
        {{ form.new_password1 }}
        <div class="">
          <span class="input-group-text" onclick="togglePasswordVisibility('id_new_password1')">
            <i class="fa fa-eye" id="togglePassword1"></i>
          </span>
        </div>
      </div>
    </div>
    <div class="mb-2">
      <li>Your password can’t be too similar to your other personal information.</li>
      <li>Your password must contain at least 8 characters.</li>
      <li>Your password can’t be a commonly used password.</li>
      <li>Your password can’t be entirely numeric.</li>
    </div>
    <div class="form-group">
      {{ form.new_password2.label_tag }}<br>
      <div class="input-group">
        {{ form.new_password2 }}
        <div class="">
          <span class="input-group-text" onclick="togglePasswordVisibility('id_new_password2')">
            <i class="fa fa-eye" id="togglePassword2"></i>
          </span>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Change password</button>
  </form>

  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="passwordChangeToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto">Notification</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
      </div>
    </div>
  </div>

  <script>
    document.getElementById('passwordChangeForm').addEventListener('submit', function(event) {
      event.preventDefault(); 
      const form = this;
      const formData = new FormData(form);

      fetch(form.action, {
        method: form.method,
        body: formData,
        headers: {
          'X-CSRFToken': formData.get('csrfmiddlewaretoken')
        }
      })
      .then(response => response.json())
      .then(data => {
        const toastElement = document.getElementById('passwordChangeToast');
        const toastBody = toastElement.querySelector('.toast-body');
        if (data.success) {
          toastBody.textContent = 'Your password was successfully changed.';
          toastElement.classList.add('text-bg-success');
        } else {
          toastBody.textContent = 'Your password could not be changed.';
          toastElement.classList.add('text-bg-danger');
        }
        const toast = new bootstrap.Toast(toastElement);
        toast.show();
      })
      .catch(error => console.error('Error:', error));
    });


    function togglePasswordVisibility(inputId) {
      const passwordInput = document.getElementById(inputId);
      const toggleIcon = passwordInput.nextElementSibling.querySelector('i');

      if (passwordInput.type === 'password') {
        passwordInput.type = 'text';
        toggleIcon.classList.remove('fa-eye-slash');
        toggleIcon.classList.add('fa-eye');
      } else {
        passwordInput.type = 'password';
        toggleIcon.classList.remove('fa-eye');
        toggleIcon.classList.add('fa-eye-slash');
      }
    }
  </script>

{% endblock %} -->

templates/edit_profile.html
<!-- edit_profile.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2>Edit Profile</h2>
    <!-- <div class="row"> -->
        <!-- <div class="col-md-6"> 
            <form method="POST" enctype="multipart/form-data" id="profile-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    {{ user_form.username }}
                </div>
                <div class="form-group">
                    <label for="id_profile_picture">Profile picture:</label>
                    {{ profile_form.profile_picture }}
                </div>
                <div class="form-group">
                    <label for="id_profile_email">Profile Email:</label>
                    {{ user_form.email }}
                </div>
                <div class="form-group">
                    <label for="id_profile_email">FirstName:</label>
                    {{ user_form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_profile_email">LastName:</label>
                    {{ user_form.last_name }}
                </div>
                
                <button type="submit" class="btn btn-primary">Update Profile</button>
            </form>
        </div> -->

        <!-- new edit-profile html content -->
         <!-- -------------------------------------------  -->

        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data" id="profile-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <input type="text" class="form-control" id="id_username" name="username" value="{{ user_form.username.value }}" required>
                </div>
                <div class="form-group">
                    <label for="id_profile_picture">Profile Picture:</label>
                    <!-- <div>
                        {% if profile_form.instance.profile_picture %}
                            <img src="{{ profile_form.instance.profile_picture.url }}" alt="Profile Picture" width="150">
                        {% else %}
                            <p>No profile picture uploaded.</p>
                        {% endif %}
                    </div> -->
                    <div class="col-sm-10">
                        {% if user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" width="100">
                        {% else %}
                            <img src="{% static 'dist/img/avatar.png' %}" alt="Default Profile Picture" class="rounded-circle" style="width: 120px; height: 120px;">
                        {% endif %}
                    </div>
                    <input type="file" class="form-control" id="id_profile_picture" name="profile_picture">
                </div>
                <div class="form-group">
                    <label for="id_email">Email Address:</label>
                    <input type="email" class="form-control" id="id_email" name="email" value="{{ user_form.email.value }}" required>
                </div>
                <div class="form-group">
                    <label for="id_first_name">First Name:</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user_form.first_name.value }}" required>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name:</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user_form.last_name.value }}" required>
                </div>
                <button type="submit" class="btn btn-primary">Update Profile</button>
            </form>
        </div>
        <hr>

        <div class="col-md-6">
            <h2>Reset Password</h2>
            <form method="POST" id="password-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_old_password">Old password:</label>
                    <div class="input-group">
                        {{ password_form.old_password }}
                        <div class="input-group-append">
                            <span class="input-group-text password-toggle-icon">
                                <i class="fas fa-eye-slash toggle-password" toggle="#id_old_password"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_new_password1">New password:</label>
                    <div class="input-group">
                        {{ password_form.new_password1 }}
                        <div class="input-group-append">
                            <span class="input-group-text password-toggle-icon">
                                <i class="fas fa-eye-slash toggle-password" toggle="#id_new_password1"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_new_password2">Confirm new password:</label>
                    <div class="input-group">
                        {{ password_form.new_password2 }}
                        <div class="input-group-append">
                            <span class="input-group-text password-toggle-icon">
                                <i class="fas fa-eye-slash toggle-password" toggle="#id_new_password2"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Reset Password</button>
            </form>
        </div>
    <!-- </div> -->
</div>


<script>
document.addEventListener('DOMContentLoaded', function() {
    const togglePassword = document.querySelectorAll('.toggle-password');
    
    togglePassword.forEach(icon => {
        icon.addEventListener('click', function() {
            const passwordField = document.querySelector(this.getAttribute('toggle'));
            const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordField.setAttribute('type', type);
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    });
});
</script>




    



 

{% endblock %}

templates/paginator.html
{% if page_obj.has_other_pages %}
<div aria-label="pagination">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}

      {% if page_obj.number == page %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">{{ page }}<span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
      {% endif %}
  </ul>
</div>

{% endif %}

templates/profile.html
<!-- profile.html -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- old profile html content -->
<!-- <div class="container mt-5"> 
    <div class="row">
        <div class="col-md-12">
            <h1>Profile</h1>
            <div class="form-group row">
                <label for="id_profile_picture" class="col-sm-2 col-form-label">Profile picture:</label>
                <div class="col-sm-10">
                    {% if user.profile.profile_picture %}
                        <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" width="100">
                    {% else %}
                        <img src="{% static 'dist/img/avatar.png' %}" alt="Default Profile Picture" class="rounded-circle" style="width: 120px; height: 120px;">
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_username" class="col-sm-2 col-form-label">Username:</label>
                <div class="col-sm-10">
                    <p class="form-control-plaintext">{{ user.username }}</p>
                </div>
            </div>
           
            <div class="form-group row">
                <label for="id_first_name" class="col-sm-2 col-form-label">First Name:</label>
                <div class="col-sm-10">
                    <p class="form-control-plaintext">{{ user.first_name }}</p>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_last_name" class="col-sm-2 col-form-label">Last Name:</label>
                <div class="col-sm-10">
                    <p class="form-control-plaintext">{{ user.last_name }}</p>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_email" class="col-sm-2 col-form-label">Email:</label>
                <div class="col-sm-10">
                    <p class="form-control-plaintext">{{ user.email }}</p>
                </div>
            </div>
        </div>
    </div>
</div> -->




<!-- new profile html content -->
<h1>Profile</h1>
<div class="row gutters-sm">

    <div class="col-md-4 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="d-flex flex-column align-items-center text-center">
            <div class="col-sm-10">
                {% if user.profile.profile_picture %}
                    <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" width="100">
                {% else %}
                    <img src="{% static 'dist/img/avatar.png' %}" alt="Default Profile Picture" class="rounded-circle" style="width: 120px; height: 120px;">
                {% endif %}
            </div>
            <div class="mt-3">
              <h4>Name: {{ user.first_name }}{{ user.last_name }}</h4>
              <h6>Email: {{ user.email}}</h6>
              <!-- <p class="text-secondary mb-1">Full Stack Developer</p>
              <p class="text-muted font-size-sm">TamilNadu,Madurai</p> -->
              <button class="btn btn-primary">Follow</button>
              <button class="btn btn-outline-primary">Message</button>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="card mt-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
            <span class="text-secondary">https://bootdey.com</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
            <span class="text-secondary">bootdey</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
            <span class="text-secondary">@bootdey</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
            <span class="text-secondary">bootdey</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
            <span class="text-secondary">bootdey</span>
          </li>
        </ul>
      </div> -->
    </div>


    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">User Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ user.username }}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">First Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ user.first_name }}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Last Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ user.last_name }}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Email</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ user.email }}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Phone</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              9876543210
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Address</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              TamilNadu,Madurai
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-12">
              <a class="btn btn-info " href="{% url 'edit_profile' %}">Edit</a>
            </div>
          </div>
        </div>
      </div>

      <!-- <div class="row gutters-sm">
        <div class="col-sm-6 mb-3">
          <div class="card h-100">
            <div class="card-body">
              <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
              <small>Web Design</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Website Markup</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>One Page</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Mobile Template</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Backend API</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 mb-3">
          <div class="card h-100">
            <div class="card-body">
              <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
              <small>Web Design</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Website Markup</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>One Page</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Mobile Template</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Backend API</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
      </div> -->



    </div>
  </div>
{% endblock %}